function varargout = Skripsi_export(varargin)

% SKRIPSI_EXPORT MATLAB code for Skripsi_export.fig
%      SKRIPSI_EXPORT, by itself, creates a new SKRIPSI_EXPORT or raises the existing
%      singleton*.
%
%      H = SKRIPSI_EXPORT returns the handle to a new SKRIPSI_EXPORT or the handle to
%      the existing singleton*.
%
%      SKRIPSI_EXPORT('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in SKRIPSI_EXPORT.M with the given input arguments.
%
%      SKRIPSI_EXPORT('Property','Value',...) creates a new SKRIPSI_EXPORT or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before Skripsi_export_OpeningFcn gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to Skripsi_export_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES

% Edit the above text to modify the response to help Skripsi_export

% Last Modified by GUIDE v2.5 04-Jan-2021 19:33:57

% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @Skripsi_export_OpeningFcn, ...
                   'gui_OutputFcn',  @Skripsi_export_OutputFcn, ...
                   'gui_LayoutFcn',  @Skripsi_export_LayoutFcn, ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end

% End initialization code - DO NOT EDIT


% --- Executes just before Skripsi_export is made visible.
function Skripsi_export_OpeningFcn(hObject, eventdata, handles, varargin)

% Choose default command line output for Skripsi_export
handles.output = hObject;

% Update handles structure
guidata(hObject, handles);

% UIWAIT makes Skripsi_export wait for user response (see UIRESUME)
% uiwait(handles.figure1);


% --- Outputs from this function are returned to the command line.
function varargout = Skripsi_export_OutputFcn(hObject, eventdata, handles) 

varargout{1} = handles.output;


% --- Executes on button press in caridata.
function bukadata_Callback(hObject, eventdata, handles)

[namaFile pathname] = uigetfile ({'*.xlsx'},'bukadata');
namaFile=fullfile(namaFile);
set(handles.namaFile,'String',namaFile);
guidata(hObject, handles);



function namaFile_Callback(hObject, eventdata, handles)

if ext == '.xlsx'
    if(exist(namaFile) == 0)
        set(hObject, 'String', 'namaFile.xlsx');
        errordlg('File tidak ada', 'Error');
    else
        handles.metricdata.namaFile = namaFile;
        guidata(hObject,handles)
    end
else
    set(hObject, 'String', 'namaFile.xlsx');
    errordlg('Nama File tidak valid', 'Error');
end




% --- Executes during object creation, after setting all properties.
function namaFile_CreateFcn(hObject, eventdata, handles)
%
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on button press in pushbutton2.
function pushbutton2_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
warndlg('Proses Training memakan waktu beberapa menit!')
% proses normalisasi data
namaFile = get(handles.namaFile,'String');
global data;
global data_norm;
global tahun_latih;
global net_keluaran;
global max_data;
global min_data;
global net_keluaran_pso;
data = xlsread(namaFile);
data(:,1) = [];
tahun_latih=size(data,1)-2;
jumlah_bulan=size(data,2);
max_data = max(max(data));
min_data = min(min(data));

[m,n] = size(data);

%normalisasi Data
data_norm = zeros(m,n);
for x = 1:m
    for y = 1:n
        data_norm(x,y) = 0.1+0.8*(data(x,y)-min_data)/(max_data-min_data);
    end
end
% menyusun data dan target latih
data_norm = data_norm';
data_latih = zeros(12,jumlah_bulan*tahun_latih);

for n = 1:jumlah_bulan*tahun_latih
    for m = 1:jumlah_bulan
        data_latih(m,n) = data_norm(m+n);
    end
end

target_latih = data_norm(jumlah_bulan+1:jumlah_bulan*(tahun_latih+1));
jumlah_neuron1 = str2double(handles.hidden.String);
fungsi_aktivasi1 = 'logsig';
fungsi_aktivasi2 = 'logsig';
fungsi_pelatihan = 'traingd';

% membangun arsitektur backpropagation
net = newff(minmax(data_latih),[jumlah_neuron1 1],{fungsi_aktivasi1,...
    fungsi_aktivasi2},fungsi_pelatihan);

% menyiapkan parameter2 pelatihan (error goal, jumlah
% epoch, laju pembelajaran)
error_goal = str2double(handles.errg.String);
jumlah_epoch = str2double(handles.epoch.String);
laju_pembelajaran = str2double(handles.learnr.String);

net.trainParam.goal = error_goal;
net.trainParam.epochs = jumlah_epoch;
net.trainParam.lr = laju_pembelajaran;

% proses pelatihan (training)
net_keluaran = train(net,data_latih,target_latih);

% hasil pelatihan
hasil_latih = sim(net_keluaran,data_latih);

% penghitungan nilai MSE & MAPE
%MSE_latih = mse(net_keluaran,hasil_latih,target_latih);
mapelatih=mean(abs(hasil_latih -  target_latih)./target_latih)*100;
RMSE = sqrt(mean((target_latih - hasil_latih).^2));
%menampilkan RMSE dan MAPE latih BPNN
set(handles.tbm,'String',RMSE);
set(handles.mplatbp,'String',mapelatih);
%set(handles.rms,'String',RMSE);
%denormalisasi data hasil backpropagation
hasil_latih = ((hasil_latih-0.1)*(max_data-min_data)/0.8)+min_data;

target_latih_asli = data(2:5,:);	% 2015 s.d 2018
target_latih_asli = target_latih_asli';
target_latih_asli = target_latih_asli(:);

% PSO
r1p=str2double(handles.rsp.String);
r2p=str2double(handles.rdp.String);
iterpso=str2double(handles.iterpso.String);
pop=str2double(handles.pop.String);
%netp = newff(minmax(data_latih),[jumlah_neuron1 1],{fungsi_aktivasi1,fungsi_aktivasi2});
%netpso = configure(netp,data_latih,target_latih);
h = @(x) NMSE(x, net_keluaran, data_latih, target_latih);
k = jumlah_neuron1;
[x_pso, ~] = pso(h, 12*k+k+k+1,iterpso,pop,r1p,r2p);
net_keluaran_pso = setwb(net_keluaran, x_pso);
hasil_latih_pso = sim(net_keluaran_pso,data_latih);

% penghitungan nilai MSE 
%MSE_latih_pso = mse(hasil_latih_pso,target_latih);
mapelatihpso=mean(abs(hasil_latih_pso - target_latih)./target_latih)*100;
RMSE_latih_PSO = sqrt(mean((target_latih - hasil_latih_pso).^2));
%menampilkan RMSE latih PSO
set(handles.tbpm,'String',RMSE_latih_PSO);
set(handles.mplatbps,'String',mapelatihpso);
%menyimpan model training backprop pso
save latihpso.mat hasil_latih_pso
%denormalisasi data hasil latih backprop pso
hasil_latih_pso = ((hasil_latih_pso-...
    0.1)*(max_data-min_data)/0.8)+min_data;

% plot grafik keluaran latih dengan target
figure,
plot(target_latih_asli,'ro-','LineWidth',1)
hold on
plot(hasil_latih,'b*-','LineWidth',1)
plot(hasil_latih_pso,'g*-','LineWidth',1)
hold off
grid on
title('Grafik Keluaran Training Data')
h = gca;
h.XTick = [1:12:60];
h.XTickLabel = {'2014';'2015';'2016';'2017';'2018'};
xlabel('Tahun')
ylabel('IHK')
legend('Target','Backpropagation','Backpropagation+PSO','Location','Best')




function tbm_Callback(hObject, eventdata, handles)
% hObject    handle to tbm (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of tbm as text
%        str2double(get(hObject,'String')) returns contents of tbm as a double


% --- Executes during object creation, after setting all properties.
function tbm_CreateFcn(hObject, eventdata, handles)

if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function tbpm_Callback(hObject, eventdata, handles)
% hObject    handle to tbpm (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of tbpm as text
%        str2double(get(hObject,'String')) returns contents of tbpm as a double
% --- Executes during object creation, after setting all properties.
function tbpm_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end

function testbpm_Callback(hObject, eventdata, handles)
% hObject    handle to testbpm (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of testbpm as text
%        str2double(get(hObject,'String')) returns contents of testbpm as a double
% --- Executes during object creation, after setting all properties.
function testbpm_CreateFcn(hObject, eventdata, handles)

if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function testbm_Callback(hObject, eventdata, handles)
% hObject    handle to testbm (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of testbm as text
%        str2double(get(hObject,'String')) returns contents of testbm as a double


% --- Executes during object creation, after setting all properties.
function testbm_CreateFcn(hObject, eventdata, handles)

if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on button press in pushbutton3.
function pushbutton3_Callback(hObject, eventdata, handles)
global data;
global data_norm;
global tahun_latih;
global net_keluaran;
global max_data;
global min_data;
global net_keluaran_pso;
if exist('latihpso.mat','file')
% load jaringan yang sudah dibuat pada proses pelatihan
load latihpso.mat
% menyusun data dan target uji
tahun_uji = 1; % Januari 2019 s.d Desember 2019
jumlah_bulan = 12;
data_uji = zeros(12,jumlah_bulan*tahun_uji-1);

for n = 1:jumlah_bulan*tahun_uji
    for m = 1:jumlah_bulan
        data_uji(m,n) = data_norm(jumlah_bulan*tahun_latih+m+n);
    end
end
 
target_uji = data_norm(jumlah_bulan*(tahun_latih+tahun_uji)+1:end); % Januari 2019 s.d Desember 2019

% hasil pengujian Backpropagation
hasil_uji = sim(net_keluaran,data_uji);

% penghitungan nilai MSE & MAPE uji Backpropagation
%MSE_uji = mse(hasil_uji,target_uji);
mapeuji=mean(abs(hasil_uji-target_uji)/target_uji)*100;
RMSE_uji=sqrt(mean((target_uji - hasil_uji).^2));
%menampilkan MSE & MAPE uji BPNN
set(handles.testbm,'String',RMSE_uji);
set(handles.mptsb,'String',mapeuji);
hasil_uji = ((hasil_uji-...
    0.1)*(max_data-min_data)/0.8)+min_data;
target_uji_asli = data(6,:);	% 2019
target_uji_asli = target_uji_asli';
target_uji_asli = target_uji_asli(:);

% hasil pengujian PSO-BPNN
hasil_uji_pso = sim(net_keluaran_pso,data_uji);

% penghitungan MSE & MAPE PSO-BPNN
%MSE_uji_pso = mse(hasil_uji_pso,target_uji);
mapepsouji=mean(abs(hasil_uji_pso-target_uji)/target_uji)*100;
RMSE_uji_pso=sqrt(mean((target_uji - hasil_uji_pso).^2));
%menampilkan MSE & MAPE uji PSO-BPNN
set(handles.testbpm,'String',RMSE_uji_pso);
set(handles.mptsbps,'String',mapepsouji);

hasil_uji_pso = ((hasil_uji_pso-...
    0.1)*(max_data-min_data)/0.8)+min_data;

figure,
plot(target_uji_asli,'mo-','LineWidth',1)
hold on
plot(hasil_uji,'y*-','LineWidth',1)
plot(hasil_uji_pso,'c*-','LineWidth',1)
hold off
grid on
title('Grafik Keluaran Testing Data')
h = gca;
h.XTick = [1:12];
h.XTickLabel = {'JAN';'FEB';'MAR';'APR';'MEI';'JUN';...
    'JUL';'AGS';'SEP';'OKT';'NOV';'DES'};
xlabel('Tahun 2019')
ylabel('IHK')
legend('Target','Backpropagation','Backpropagation+PSO','Location','Best')
else 
    errordlg('Model training tidak di temukan, Lakukan training data terlebih dahulu!!!')
end


function input1_Callback(hObject, eventdata, handles)
% hObject    handle to input1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of input1 as text
%        str2double(get(hObject,'String')) returns contents of input1 as a double


% --- Executes during object creation, after setting all properties.
function input1_CreateFcn(hObject, eventdata, handles)
% hObject    handle to input1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function input2_Callback(hObject, eventdata, handles)
% hObject    handle to input2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of input2 as text
%        str2double(get(hObject,'String')) returns contents of input2 as a double


% --- Executes during object creation, after setting all properties.
function input2_CreateFcn(hObject, eventdata, handles)
% hObject    handle to input2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function input3_Callback(hObject, eventdata, handles)
% hObject    handle to input3 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of input3 as text
%        str2double(get(hObject,'String')) returns contents of input3 as a double


% --- Executes during object creation, after setting all properties.
function input3_CreateFcn(hObject, eventdata, handles)
% hObject    handle to input3 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function input4_Callback(hObject, eventdata, handles)
% hObject    handle to input4 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of input4 as text
%        str2double(get(hObject,'String')) returns contents of input4 as a double


% --- Executes during object creation, after setting all properties.
function input4_CreateFcn(hObject, eventdata, handles)
% hObject    handle to input4 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function input5_Callback(hObject, eventdata, handles)
% hObject    handle to input5 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of input5 as text
%        str2double(get(hObject,'String')) returns contents of input5 as a double


% --- Executes during object creation, after setting all properties.
function input5_CreateFcn(hObject, eventdata, handles)
% hObject    handle to input5 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function input6_Callback(hObject, eventdata, handles)
% hObject    handle to input6 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of input6 as text
%        str2double(get(hObject,'String')) returns contents of input6 as a double


% --- Executes during object creation, after setting all properties.
function input6_CreateFcn(hObject, eventdata, handles)
% hObject    handle to input6 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function input7_Callback(hObject, eventdata, handles)
% hObject    handle to input7 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of input7 as text
%        str2double(get(hObject,'String')) returns contents of input7 as a double


% --- Executes during object creation, after setting all properties.
function input7_CreateFcn(hObject, eventdata, handles)
% hObject    handle to input7 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function input8_Callback(hObject, eventdata, handles)
% hObject    handle to input8 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of input8 as text
%        str2double(get(hObject,'String')) returns contents of input8 as a double


% --- Executes during object creation, after setting all properties.
function input8_CreateFcn(hObject, eventdata, handles)
% hObject    handle to input8 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function input9_Callback(hObject, eventdata, handles)
% hObject    handle to input9 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of input9 as text
%        str2double(get(hObject,'String')) returns contents of input9 as a double


% --- Executes during object creation, after setting all properties.
function input9_CreateFcn(hObject, eventdata, handles)
% hObject    handle to input9 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function input10_Callback(hObject, eventdata, handles)
% hObject    handle to input10 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of input10 as text
%        str2double(get(hObject,'String')) returns contents of input10 as a double


% --- Executes during object creation, after setting all properties.
function input10_CreateFcn(hObject, eventdata, handles)
% hObject    handle to input10 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function input11_Callback(hObject, eventdata, handles)
% hObject    handle to input11 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of input11 as text
%        str2double(get(hObject,'String')) returns contents of input11 as a double


% --- Executes during object creation, after setting all properties.
function input11_CreateFcn(hObject, eventdata, handles)
% hObject    handle to input11 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function input12_Callback(hObject, eventdata, handles)
% hObject    handle to input12 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of input12 as text
%        str2double(get(hObject,'String')) returns contents of input12 as a double


% --- Executes during object creation, after setting all properties.
function input12_CreateFcn(hObject, eventdata, handles)
% hObject    handle to input12 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on button press in pushbutton4.
function pushbutton4_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton4 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
global data;
global max_data;
global min_data;
global net_keluaran_pso;

x1=str2double(handles.input1.String); x2=str2double(handles.input2.String); x3=str2double(handles.input3.String);
x4=str2double(handles.input4.String); x5=str2double(handles.input5.String); x6=str2double(handles.input6.String);
x7=str2double(handles.input7.String); x8=str2double(handles.input8.String); x9=str2double(handles.input9.String);
x10=str2double(handles.input10.String);x11=str2double(handles.input11.String);x12=str2double(handles.input12.String);
datap=[x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12];

  
max_data = max(max(data));
min_data = min(min(data));
  
[m,n] = size(datap);

data_normp = zeros(m,n);
for x = 1:m
    for y = 1:n
        data_normp(x,y) = 0.1+0.8*(datap(x,y)-min_data)/(max_data-min_data);
    end
end

data_pred = reshape(data_normp,12,1);
 


hasil = sim(net_keluaran_pso,data_pred);
hasil = ((hasil-0.1)*(max_data-min_data)/0.8)+min_data;
set(handles.hasilp,'String',hasil);



function hasilp_Callback(hObject, eventdata, handles)
% hObject    handle to hasilp (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of hasilp as text
%        str2double(get(hObject,'String')) returns contents of hasilp as a double


% --- Executes during object creation, after setting all properties.
function hasilp_CreateFcn(hObject, eventdata, handles)
% hObject    handle to hasilp (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function mplatbp_Callback(hObject, eventdata, handles)
% hObject    handle to mplatbp (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of mplatbp as text
%        str2double(get(hObject,'String')) returns contents of mplatbp as a double


% --- Executes during object creation, after setting all properties.
function mplatbp_CreateFcn(hObject, eventdata, handles)
% hObject    handle to mplatbp (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end




function mptsb_Callback(hObject, eventdata, handles)
% hObject    handle to mptsb (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of mptsb as text
%        str2double(get(hObject,'String')) returns contents of mptsb as a double


% --- Executes during object creation, after setting all properties.
function mptsb_CreateFcn(hObject, eventdata, handles)
% hObject    handle to mptsb (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function mptsbps_Callback(hObject, eventdata, handles)
% hObject    handle to mptsbps (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of mptsbps as text
%        str2double(get(hObject,'String')) returns contents of mptsbps as a double


% --- Executes during object creation, after setting all properties.
function mptsbps_CreateFcn(hObject, eventdata, handles)
% hObject    handle to mptsbps (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function hidden_Callback(hObject, eventdata, handles)
% hObject    handle to hidden (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of hidden as text
%        str2double(get(hObject,'String')) returns contents of hidden as a double


% --- Executes during object creation, after setting all properties.
function hidden_CreateFcn(hObject, eventdata, handles)
% hObject    handle to hidden (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function learnr_Callback(hObject, eventdata, handles)
% hObject    handle to learnr (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of learnr as text
%        str2double(get(hObject,'String')) returns contents of learnr as a double


% --- Executes during object creation, after setting all properties.
function learnr_CreateFcn(hObject, eventdata, handles)
% hObject    handle to learnr (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function epoch_Callback(hObject, eventdata, handles)
% hObject    handle to epoch (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of epoch as text
%        str2double(get(hObject,'String')) returns contents of epoch as a double


% --- Executes during object creation, after setting all properties.
function epoch_CreateFcn(hObject, eventdata, handles)
% hObject    handle to epoch (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function errg_Callback(hObject, eventdata, handles)
% hObject    handle to errg (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of errg as text
%        str2double(get(hObject,'String')) returns contents of errg as a double


% --- Executes during object creation, after setting all properties.
function errg_CreateFcn(hObject, eventdata, handles)
% hObject    handle to errg (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function mplatbps_Callback(hObject, eventdata, handles)
% hObject    handle to mplatbps (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of mplatbps as text
%        str2double(get(hObject,'String')) returns contents of mplatbps as a double


% --- Executes during object creation, after setting all properties.
function mplatbps_CreateFcn(hObject, eventdata, handles)
% hObject    handle to mplatbps (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function edit37_Callback(hObject, eventdata, handles)
% hObject    handle to edit37 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of edit37 as text
%        str2double(get(hObject,'String')) returns contents of edit37 as a double


% --- Executes during object creation, after setting all properties.
function edit37_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit37 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function edit36_Callback(hObject, eventdata, handles)
% hObject    handle to edit36 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of edit36 as text
%        str2double(get(hObject,'String')) returns contents of edit36 as a double


% --- Executes during object creation, after setting all properties.
function edit36_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit36 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function edit35_Callback(hObject, eventdata, handles)
% hObject    handle to edit35 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of edit35 as text
%        str2double(get(hObject,'String')) returns contents of edit35 as a double


% --- Executes during object creation, after setting all properties.
function edit35_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit35 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function edit34_Callback(hObject, eventdata, handles)
% hObject    handle to edit34 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of edit34 as text
%        str2double(get(hObject,'String')) returns contents of edit34 as a double


% --- Executes during object creation, after setting all properties.
function edit34_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit34 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function rsp_Callback(hObject, eventdata, handles)
% hObject    handle to rsp (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of rsp as text
%        str2double(get(hObject,'String')) returns contents of rsp as a double


% --- Executes during object creation, after setting all properties.
function rsp_CreateFcn(hObject, eventdata, handles)
% hObject    handle to rsp (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function rdp_Callback(hObject, eventdata, handles)
% hObject    handle to rdp (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of rdp as text
%        str2double(get(hObject,'String')) returns contents of rdp as a double


% --- Executes during object creation, after setting all properties.
function rdp_CreateFcn(hObject, eventdata, handles)
% hObject    handle to rdp (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function iterpso_Callback(hObject, eventdata, handles)
% hObject    handle to iterpso (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of iterpso as text
%        str2double(get(hObject,'String')) returns contents of iterpso as a double


% --- Executes during object creation, after setting all properties.
function iterpso_CreateFcn(hObject, eventdata, handles)
% hObject    handle to iterpso (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function pop_Callback(hObject, eventdata, handles)
% hObject    handle to pop (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of pop as text
%        str2double(get(hObject,'String')) returns contents of pop as a double


% --- Executes during object creation, after setting all properties.
function pop_CreateFcn(hObject, eventdata, handles)
% hObject    handle to pop (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function rms_Callback(hObject, eventdata, handles)
% hObject    handle to rms (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of rms as text
%        str2double(get(hObject,'String')) returns contents of rms as a double


% --- Executes during object creation, after setting all properties.
function rms_CreateFcn(hObject, eventdata, handles)
% hObject    handle to rms (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Creates and returns a handle to the GUI figure. 
function h1 = Skripsi_export_LayoutFcn(policy)
% policy - create a new figure or use a singleton. 'new' or 'reuse'.

persistent hsingleton;
if strcmpi(policy, 'reuse') & ishandle(hsingleton)
    h1 = hsingleton;
    return;
end
load Skripsi_export.mat


appdata = [];
appdata.GUIDEOptions = mat{1};
appdata.lastValidTag = 'figure1';
appdata.GUIDELayoutEditor = [];
appdata.initTags = struct(...
    'handle', [], ...
    'tag', 'figure1');

h1 = figure(...
'Units','characters',...
'Position',[135.8 30.7692307692308 216 53.6153846153846],...
'Visible',get(0,'defaultfigureVisible'),...
'Color',[0.941176470588235 0.941176470588235 0.941176470588235],...
'CurrentAxesMode','manual',...
'IntegerHandle','off',...
'MenuBar','none',...
'Name','Skripsi',...
'NumberTitle','off',...
'Tag','figure1',...
'Resize','off',...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'ScreenPixelsPerInchMode','manual',...
'HandleVisibility','callback',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel8';

h2 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'HighlightColor',[0 0 0],...
'ShadowColor',[0 0 0],...
'BorderType',get(0,'defaultuipanelBorderType'),...
'BorderWidth',get(0,'defaultuipanelBorderWidth'),...
'TitlePosition','centertop',...
'Title','Olah Data',...
'Tag','uipanel8',...
'Position',[0.6 0.846153846153846 122.4 52.4615384615385],...
'FontSize',13,...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel1';

h3 = uipanel(...
'Parent',h2,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'ForegroundColor',get(0,'defaultuipanelForegroundColor'),...
'HighlightColor',[0 0 0],...
'ShadowColor',[0.498039215686275 0.549019607843137 0.552941176470588],...
'Title','Input Data',...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Tag','uipanel1',...
'Position',[19.2 41.6153846153846 77.8 8.61538461538462],...
'HandleVisibility',get(0,'defaultuipanelHandleVisibility'),...
'FontSize',11,...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'namaFile';

h4 = uicontrol(...
'Parent',h3,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','namafile.xlsx',...
'Style','edit',...
'Position',[29.6 3.15384615384615 43.8 1.76923076923077],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('namaFile_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('namaFile_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','namaFile');

appdata = [];
appdata.lastValidTag = 'bukadata';

h5 = uicontrol(...
'Parent',h3,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Cari Data (.xlsx)',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[2.4 3.07692307692308 25.8 1.69230769230769],...
'BackgroundColor',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Callback',@(hObject,eventdata)Skripsi_export('bukadata_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Tag','bukadata',...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'pushbutton2';

h6 = uicontrol(...
'Parent',h2,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Training Data',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[38 26.9230769230769 17.2 1.84615384615385],...
'Callback',@(hObject,eventdata)Skripsi_export('pushbutton2_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tag','pushbutton2',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'pushbutton3';

h7 = uicontrol(...
'Parent',h2,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Testing Data',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[58.6 26.9230769230769 17 1.76923076923077],...
'Callback',@(hObject,eventdata)Skripsi_export('pushbutton3_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tag','pushbutton3',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel3';

h8 = uipanel(...
'Parent',h2,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'HighlightColor',[0 0 0],...
'TitlePosition','centertop',...
'Title','Hasil Pengujian MSE dan MAPE',...
'BackgroundColor',get(0,'defaultuipanelBackgroundColor'),...
'Tag','uipanel3',...
'Position',[4.8 1.76923076923077 109.2 24.1538461538462],...
'FontSize',11,...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel7';

h9 = uipanel(...
'Parent',h8,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Testing',...
'ResizeFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','uipanel7',...
'Position',[57.6 1.76923076923077 48.2 19.1538461538462]);

appdata = [];
appdata.lastValidTag = 'testbpm';

h10 = uicontrol(...
'Parent',h9,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[11.2 3.76923076923077 30.6 2.07692307692308],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('testbpm_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('testbpm_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','testbpm',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'text13';

h11 = uicontrol(...
'Parent',h9,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Backpropagation + PSO',...
'Style','text',...
'Position',[6 5.84615384615385 25 2],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text13');

appdata = [];
appdata.lastValidTag = 'testbm';

h12 = uicontrol(...
'Parent',h9,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[11.6 13.5384615384615 21.8 1.46153846153846],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('testbm_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('testbm_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','testbm',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'text12';

h13 = uicontrol(...
'Parent',h9,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Backpropagation',...
'Style','text',...
'Position',[8.6 15.3076923076923 20.2 1.84615384615384],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text12');

appdata = [];
appdata.lastValidTag = 'text34';

h14 = uicontrol(...
'Parent',h9,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','RMSE',...
'Style','text',...
'Position',[0.6 13.7692307692308 10.4 1.07692307692308],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text34');

appdata = [];
appdata.lastValidTag = 'text35';

h15 = uicontrol(...
'Parent',h9,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','RMSE',...
'Style','text',...
'Position',[0.6 4.38461538461539 10.4 1.07692307692308],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text35');

appdata = [];
appdata.lastValidTag = 'text36';

h16 = uicontrol(...
'Parent',h9,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','MAPE',...
'Style','text',...
'Position',[0.6 11.3846153846154 10.4 1.07692307692308],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text36');

appdata = [];
appdata.lastValidTag = 'mptsb';

h17 = uicontrol(...
'Parent',h9,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[11.6 11.3846153846154 21.8 1.46153846153846],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('mptsb_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('mptsb_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','mptsb',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'text37';

h18 = uicontrol(...
'Parent',h9,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','MAPE',...
'Style','text',...
'Position',[0.6 1.46153846153846 10.4 1.15384615384615],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text37');

appdata = [];
appdata.lastValidTag = 'mptsbps';

h19 = uicontrol(...
'Parent',h9,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[11 1.07692307692308 30.6 2.07692307692308],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('mptsbps_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('mptsbps_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','mptsbps',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'text40';

h20 = uicontrol(...
'Parent',h9,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','%',...
'Style','text',...
'Position',[33.8 11.6153846153846 4 1.07692307692308],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text40');

appdata = [];
appdata.lastValidTag = 'text41';

h21 = uicontrol(...
'Parent',h9,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','%',...
'Style','text',...
'Position',[42 1.53846153846154 4 1.07692307692308],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text41');

appdata = [];
appdata.lastValidTag = 'uipanel4';

h22 = uipanel(...
'Parent',h8,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Training',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','uipanel4',...
'Position',[5.8 1.61538461538461 47.2 19.3846153846154]);

appdata = [];
appdata.lastValidTag = 'text4';

h23 = uicontrol(...
'Parent',h22,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Backpropagation',...
'Style','text',...
'Position',[8.6 15.3076923076923 20.2 1.84615384615384],...
'Children',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','text4');

appdata = [];
appdata.lastValidTag = 'tbm';

h24 = uicontrol(...
'Parent',h22,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[11.2 13.5384615384615 21.8 1.46153846153846],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('tbm_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('tbm_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','tbm');

appdata = [];
appdata.lastValidTag = 'text5';

h25 = uicontrol(...
'Parent',h22,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Backpropagation + PSO',...
'Style','text',...
'Position',[6 5.84615384615385 25 2],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text5');

appdata = [];
appdata.lastValidTag = 'tbpm';

h26 = uicontrol(...
'Parent',h22,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[11.2 3.76923076923077 30.6 2.07692307692308],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('tbpm_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('tbpm_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','tbpm',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'text29';

h27 = uicontrol(...
'Parent',h22,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','RMSE',...
'Style','text',...
'Position',[0.6 13.6923076923077 10.4 1.07692307692308],...
'Children',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','text29');

appdata = [];
appdata.lastValidTag = 'text31';

h28 = uicontrol(...
'Parent',h22,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','RMSE',...
'Style','text',...
'Position',[0.6 4.38461538461539 10.4 1.07692307692308],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text31');

appdata = [];
appdata.lastValidTag = 'text46';

h29 = uicontrol(...
'Parent',h22,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','MAPE',...
'Style','text',...
'Position',[1.4 11.3846153846154 9.2 1.07692307692308],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text46');

appdata = [];
appdata.lastValidTag = 'mplatbp';

h30 = uicontrol(...
'Parent',h22,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[11.2 11.3846153846154 21.8 1.46153846153846],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('mplatbp_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('mplatbp_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','mplatbp',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'text47';

h31 = uicontrol(...
'Parent',h22,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','%',...
'Style','text',...
'Position',[33.4 11.6153846153846 4 1.07692307692308],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text47');

appdata = [];
appdata.lastValidTag = 'text48';

h32 = uicontrol(...
'Parent',h22,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','MAPE',...
'Style','text',...
'Position',[0.8 1.76923076923077 10.4 1.15384615384615],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text48');

appdata = [];
appdata.lastValidTag = 'mplatbps';

h33 = uicontrol(...
'Parent',h22,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[11.2 1.38461538461538 30.6 2.07692307692308],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('mplatbps_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('mplatbps_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','mplatbps',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'text49';

h34 = uicontrol(...
'Parent',h22,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','%',...
'Style','text',...
'Position',[42.2 1.84615384615385 4 1.07692307692308],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text49');

appdata = [];
appdata.lastValidTag = 'uipanel11';

h35 = uipanel(...
'Parent',h2,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Parameter Backpropagation',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','uipanel11',...
'Position',[18.6 29.8461538461538 38.2 11.5384615384615]);

appdata = [];
appdata.lastValidTag = 'hidden';

h36 = uicontrol(...
'Parent',h35,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[18.4 7.30769230769231 12.8 1.15384615384615],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('hidden_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('hidden_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','hidden');

appdata = [];
appdata.lastValidTag = 'learnr';

h37 = uicontrol(...
'Parent',h35,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[18.4 5 13.2 1.07692307692308],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('learnr_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('learnr_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','learnr');

appdata = [];
appdata.lastValidTag = 'epoch';

h38 = uicontrol(...
'Parent',h35,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[18.2 2.69230769230769 13 1.23076923076923],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('epoch_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('epoch_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','epoch');

appdata = [];
appdata.lastValidTag = 'errg';

h39 = uicontrol(...
'Parent',h35,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[18.4 0.923076923076923 12.6 1.07692307692308],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('errg_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('errg_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','errg');

appdata = [];
appdata.lastValidTag = 'text42';

h40 = uicontrol(...
'Parent',h35,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Hidden Layer',...
'Style','text',...
'Position',[1.4 7.30769230769231 16.8 1.07692307692308],...
'Children',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','text42');

appdata = [];
appdata.lastValidTag = 'text43';

h41 = uicontrol(...
'Parent',h35,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Learning Rate',...
'Style','text',...
'Position',[0.6 5 16.8 1.07692307692308],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text43');

appdata = [];
appdata.lastValidTag = 'text44';

h42 = uicontrol(...
'Parent',h35,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Epoch',...
'Style','text',...
'Position',[0.6 2.76923076923077 16.8 1.07692307692308],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text44');

appdata = [];
appdata.lastValidTag = 'text45';

h43 = uicontrol(...
'Parent',h35,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Error Goal',...
'Style','text',...
'Position',[1 0.923076923076923 16.8 1.07692307692308],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text45');

appdata = [];
appdata.lastValidTag = 'uipanel12';

h44 = uipanel(...
'Parent',h2,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'Title','Parameter PSO',...
'ResizeFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','uipanel12',...
'Position',[59.4 29.8461538461538 38.2 11.5384615384615]);

appdata = [];
appdata.lastValidTag = 'text53';

h45 = uicontrol(...
'Parent',h44,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Populasi',...
'Style','text',...
'Position',[1 0.923076923076923 16.8 1.07692307692308],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text53');

appdata = [];
appdata.lastValidTag = 'text52';

h46 = uicontrol(...
'Parent',h44,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','iterasi',...
'Style','text',...
'Position',[0.6 2.76923076923077 16.8 1.07692307692308],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text52');

appdata = [];
appdata.lastValidTag = 'text51';

h47 = uicontrol(...
'Parent',h44,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','r2',...
'Style','text',...
'Position',[1 5 16.8 1.07692307692308],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text51');

appdata = [];
appdata.lastValidTag = 'text50';

h48 = uicontrol(...
'Parent',h44,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','r1',...
'Style','text',...
'Position',[1.4 7.23076923076923 16.8 1.15384615384615],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text50');

appdata = [];
appdata.lastValidTag = 'rsp';

h49 = uicontrol(...
'Parent',h44,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[16.6 7.30769230769231 15.6 1.15384615384615],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('rsp_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('rsp_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','rsp');

appdata = [];
appdata.lastValidTag = 'rdp';

h50 = uicontrol(...
'Parent',h44,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[16.6 4.92307692307692 15.6 1.15384615384615],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('rdp_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('rdp_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','rdp',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'iterpso';

h51 = uicontrol(...
'Parent',h44,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[16.4 2.76923076923077 15.6 1.15384615384615],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('iterpso_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('iterpso_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','iterpso',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'pop';

h52 = uicontrol(...
'Parent',h44,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[16.4 0.923076923076923 15.6 1.15384615384615],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('pop_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('pop_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pop',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'uipanel9';

h53 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'HighlightColor',[0 0 0],...
'ShadowColor',[0 0 0],...
'TitlePosition','centertop',...
'Title','Prediksi IHK',...
'Tag','uipanel9',...
'Position',[123.4 0.846153846153846 89 52.4615384615385],...
'FontSize',13,...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text15';

h54 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','X1',...
'Style','text',...
'Position',[4.8 42.6923076923077 14.4 1.46153846153846],...
'Children',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','text15',...
'FontSize',10);

appdata = [];
appdata.lastValidTag = 'text16';

h55 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','X2',...
'Style','text',...
'Position',[4.8 40.2307692307692 14.4 1.61538461538461],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text16',...
'FontSize',10);

appdata = [];
appdata.lastValidTag = 'text17';

h56 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','X3',...
'Style','text',...
'Position',[4.8 37.8461538461539 14.4 1.61538461538461],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text17',...
'FontSize',10);

appdata = [];
appdata.lastValidTag = 'text18';

h57 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','X4',...
'Style','text',...
'Position',[4.8 35.6153846153846 14.4 1.61538461538461],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text18',...
'FontSize',10);

appdata = [];
appdata.lastValidTag = 'text19';

h58 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','X5',...
'Style','text',...
'Position',[5 33.3846153846154 14.4 1.61538461538461],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text19',...
'FontSize',10);

appdata = [];
appdata.lastValidTag = 'text20';

h59 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','X6',...
'Style','text',...
'Position',[4.8 31.0769230769231 14.4 1.61538461538462],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text20',...
'FontSize',10);

appdata = [];
appdata.lastValidTag = 'input1';

h60 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[14.2 42.7692307692308 23 1.46153846153846],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('input1_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('input1_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','input1');

appdata = [];
appdata.lastValidTag = 'input2';

h61 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[14.2 40.4615384615385 23 1.46153846153846],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('input2_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('input2_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','input2',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'input3';

h62 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[14.2 38.1538461538462 23 1.46153846153846],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('input3_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('input3_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','input3',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'input4';

h63 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[14.2 35.7692307692308 23 1.46153846153846],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('input4_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('input4_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','input4',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'input5';

h64 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[14.2 33.5384615384615 23 1.46153846153846],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('input5_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('input5_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','input5',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'input6';

h65 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[14.2 31.2307692307692 23 1.46153846153846],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('input6_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('input6_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','input6',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'text21';

h66 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','X7',...
'Style','text',...
'Position',[47 42.9230769230769 14.4 1.46153846153846],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text21',...
'FontSize',10);

appdata = [];
appdata.lastValidTag = 'text22';

h67 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','X8',...
'Style','text',...
'Position',[47 40.4615384615385 14.4 1.61538461538461],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text22',...
'FontSize',10);

appdata = [];
appdata.lastValidTag = 'text23';

h68 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','X9',...
'Style','text',...
'Position',[47 38.0769230769231 14.4 1.61538461538461],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text23',...
'FontSize',10);

appdata = [];
appdata.lastValidTag = 'text24';

h69 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','X10',...
'Style','text',...
'Position',[46.6 35.7692307692308 14.4 1.61538461538461],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text24',...
'FontSize',10);

appdata = [];
appdata.lastValidTag = 'text25';

h70 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','X11',...
'Style','text',...
'Position',[46.6 33.5384615384615 14.4 1.61538461538461],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text25',...
'FontSize',10);

appdata = [];
appdata.lastValidTag = 'text26';

h71 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','X12',...
'Style','text',...
'Position',[46.6 31.2307692307692 14.4 1.61538461538462],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text26',...
'FontSize',10);

appdata = [];
appdata.lastValidTag = 'input7';

h72 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[56.4 43 23 1.46153846153846],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('input7_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('input7_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','input7',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'input8';

h73 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[56.4 40.6923076923077 23 1.46153846153846],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('input8_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('input8_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','input8',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'input9';

h74 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[56.4 38.3846153846154 23 1.46153846153846],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('input9_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('input9_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','input9',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'input10';

h75 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[56.4 36 23 1.46153846153846],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('input10_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('input10_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','input10',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'input11';

h76 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[56.4 33.7692307692308 23 1.46153846153846],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('input11_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('input11_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','input11',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'input12';

h77 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[56.4 31.4615384615385 23 1.46153846153846],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('input12_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('input12_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','input12',...
'KeyPressFcn',blanks(0));

appdata = [];
appdata.lastValidTag = 'pushbutton4';

h78 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Prediksi',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[37 28.3846153846154 16.6 1.76923076923077],...
'Callback',@(hObject,eventdata)Skripsi_export('pushbutton4_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tag','pushbutton4',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text27';

h79 = uicontrol(...
'Parent',h53,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String','Input Data IHK 12 Bulan Terakhir',...
'Style','text',...
'Position',[21.2 45.6153846153846 46.8 1.61538461538461],...
'Children',[],...
'Tag','text27',...
'FontSize',10,...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel10';

h80 = uipanel(...
'Parent',h53,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units','characters',...
'TitlePosition','centertop',...
'Title','Hasil Prediksi IHK ',...
'Tag','uipanel10',...
'Position',[17 19.6153846153846 56.8 6.76923076923077],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'hasilp';

h81 = uicontrol(...
'Parent',h80,...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'Units','characters',...
'String',blanks(0),...
'Style','edit',...
'Position',[13 1.76923076923077 29.8 2.15384615384615],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)Skripsi_export('hasilp_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)Skripsi_export('hasilp_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','hasilp');


hsingleton = h1;


% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end


% --- Handles default GUIDE GUI creation and callback dispatch
function varargout = gui_mainfcn(gui_State, varargin)

gui_StateFields =  {'gui_Name'
    'gui_Singleton'
    'gui_OpeningFcn'
    'gui_OutputFcn'
    'gui_LayoutFcn'
    'gui_Callback'};
gui_Mfile = '';
for i=1:length(gui_StateFields)
    if ~isfield(gui_State, gui_StateFields{i})
        error(message('MATLAB:guide:StateFieldNotFound', gui_StateFields{ i }, gui_Mfile));
    elseif isequal(gui_StateFields{i}, 'gui_Name')
        gui_Mfile = [gui_State.(gui_StateFields{i}), '.m'];
    end
end

numargin = length(varargin);

if numargin == 0
    % SKRIPSI_EXPORT
    % create the GUI only if we are not in the process of loading it
    % already
    gui_Create = true;
elseif local_isInvokeActiveXCallback(gui_State, varargin{:})
    % SKRIPSI_EXPORT(ACTIVEX,...)
    vin{1} = gui_State.gui_Name;
    vin{2} = [get(varargin{1}.Peer, 'Tag'), '_', varargin{end}];
    vin{3} = varargin{1};
    vin{4} = varargin{end-1};
    vin{5} = guidata(varargin{1}.Peer);
    feval(vin{:});
    return;
elseif local_isInvokeHGCallback(gui_State, varargin{:})
    % SKRIPSI_EXPORT('CALLBACK',hObject,eventData,handles,...)
    gui_Create = false;
else
    % SKRIPSI_EXPORT(...)
    % create the GUI and hand varargin to the openingfcn
    gui_Create = true;
end

if ~gui_Create
    % In design time, we need to mark all components possibly created in
    % the coming callback evaluation as non-serializable. This way, they
    % will not be brought into GUIDE and not be saved in the figure file
    % when running/saving the GUI from GUIDE.
    designEval = false;
    if (numargin>1 && ishghandle(varargin{2}))
        fig = varargin{2};
        while ~isempty(fig) && ~ishghandle(fig,'figure')
            fig = get(fig,'parent');
        end
        
        designEval = isappdata(0,'CreatingGUIDEFigure') || (isscalar(fig)&&isprop(fig,'GUIDEFigure'));
    end
        
    if designEval
        beforeChildren = findall(fig);
    end
    
    % evaluate the callback now
    varargin{1} = gui_State.gui_Callback;
    if nargout
        [varargout{1:nargout}] = feval(varargin{:});
    else       
        feval(varargin{:});
    end
    
    % Set serializable of objects created in the above callback to off in
    % design time. Need to check whether figure handle is still valid in
    % case the figure is deleted during the callback dispatching.
    if designEval && ishghandle(fig)
        set(setdiff(findall(fig),beforeChildren), 'Serializable','off');
    end
else
    if gui_State.gui_Singleton
        gui_SingletonOpt = 'reuse';
    else
        gui_SingletonOpt = 'new';
    end

    % Check user passing 'visible' P/V pair first so that its value can be
    % used by oepnfig to prevent flickering
    gui_Visible = 'auto';
    gui_VisibleInput = '';
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        % Recognize 'visible' P/V pair
        len1 = min(length('visible'),length(varargin{index}));
        len2 = min(length('off'),length(varargin{index+1}));
        if ischar(varargin{index+1}) && strncmpi(varargin{index},'visible',len1) && len2 > 1
            if strncmpi(varargin{index+1},'off',len2)
                gui_Visible = 'invisible';
                gui_VisibleInput = 'off';
            elseif strncmpi(varargin{index+1},'on',len2)
                gui_Visible = 'visible';
                gui_VisibleInput = 'on';
            end
        end
    end
    
    % Open fig file with stored settings.  Note: This executes all component
    % specific CreateFunctions with an empty HANDLES structure.

    
    % Do feval on layout code in m-file if it exists
    gui_Exported = ~isempty(gui_State.gui_LayoutFcn);
    % this application data is used to indicate the running mode of a GUIDE
    % GUI to distinguish it from the design mode of the GUI in GUIDE. it is
    % only used by actxproxy at this time.   
    setappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]),1);
    if gui_Exported
        gui_hFigure = feval(gui_State.gui_LayoutFcn, gui_SingletonOpt);

        % make figure invisible here so that the visibility of figure is
        % consistent in OpeningFcn in the exported GUI case
        if isempty(gui_VisibleInput)
            gui_VisibleInput = get(gui_hFigure,'Visible');
        end
        set(gui_hFigure,'Visible','off')

        % openfig (called by local_openfig below) does this for guis without
        % the LayoutFcn. Be sure to do it here so guis show up on screen.
        movegui(gui_hFigure,'onscreen');
    else
        gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        % If the figure has InGUIInitialization it was not completely created
        % on the last pass.  Delete this handle and try again.
        if isappdata(gui_hFigure, 'InGUIInitialization')
            delete(gui_hFigure);
            gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        end
    end
    if isappdata(0, genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]))
        rmappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]));
    end

    % Set flag to indicate starting GUI initialization
    setappdata(gui_hFigure,'InGUIInitialization',1);

    % Fetch GUIDE Application options
    gui_Options = getappdata(gui_hFigure,'GUIDEOptions');
    % Singleton setting in the GUI MATLAB code file takes priority if different
    gui_Options.singleton = gui_State.gui_Singleton;

    if ~isappdata(gui_hFigure,'GUIOnScreen')
        % Adjust background color
        if gui_Options.syscolorfig
            set(gui_hFigure,'Color', get(0,'DefaultUicontrolBackgroundColor'));
        end

        % Generate HANDLES structure and store with GUIDATA. If there is
        % user set GUI data already, keep that also.
        data = guidata(gui_hFigure);
        handles = guihandles(gui_hFigure);
        if ~isempty(handles)
            if isempty(data)
                data = handles;
            else
                names = fieldnames(handles);
                for k=1:length(names)
                    data.(char(names(k)))=handles.(char(names(k)));
                end
            end
        end
        guidata(gui_hFigure, data);
    end

    % Apply input P/V pairs other than 'visible'
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        len1 = min(length('visible'),length(varargin{index}));
        if ~strncmpi(varargin{index},'visible',len1)
            try set(gui_hFigure, varargin{index}, varargin{index+1}), catch break, end
        end
    end

    % If handle visibility is set to 'callback', turn it on until finished
    % with OpeningFcn
    gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
    if strcmp(gui_HandleVisibility, 'callback')
        set(gui_hFigure,'HandleVisibility', 'on');
    end

    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        % Handle the default callbacks of predefined toolbar tools in this
        % GUI, if any
        guidemfile('restoreToolbarToolPredefinedCallback',gui_hFigure); 
        
        % Update handle visibility
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);

        % Call openfig again to pick up the saved visibility or apply the
        % one passed in from the P/V pairs
        if ~gui_Exported
            gui_hFigure = local_openfig(gui_State.gui_Name, 'reuse',gui_Visible);
        elseif ~isempty(gui_VisibleInput)
            set(gui_hFigure,'Visible',gui_VisibleInput);
        end
        if strcmpi(get(gui_hFigure, 'Visible'), 'on')
            figure(gui_hFigure);
            
            if gui_Options.singleton
                setappdata(gui_hFigure,'GUIOnScreen', 1);
            end
        end

        % Done with GUI initialization
        if isappdata(gui_hFigure,'InGUIInitialization')
            rmappdata(gui_hFigure,'InGUIInitialization');
        end

        % If handle visibility is set to 'callback', turn it on until
        % finished with OutputFcn
        gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
        if strcmp(gui_HandleVisibility, 'callback')
            set(gui_hFigure,'HandleVisibility', 'on');
        end
        gui_Handles = guidata(gui_hFigure);
    else
        gui_Handles = [];
    end

    if nargout
        [varargout{1:nargout}] = feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    else
        feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    end

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);
    end
end

function gui_hFigure = local_openfig(name, singleton, visible)

% openfig with three arguments was new from R13. Try to call that first, if
% failed, try the old openfig.
if nargin('openfig') == 2
    % OPENFIG did not accept 3rd input argument until R13,
    % toggle default figure visible to prevent the figure
    % from showing up too soon.
    gui_OldDefaultVisible = get(0,'defaultFigureVisible');
    set(0,'defaultFigureVisible','off');
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton);
    set(0,'defaultFigureVisible',gui_OldDefaultVisible);
else
    % Call version of openfig that accepts 'auto' option"
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton, visible);  
%     %workaround for CreateFcn not called to create ActiveX
%         peers=findobj(findall(allchild(gui_hFigure)),'type','uicontrol','style','text');    
%         for i=1:length(peers)
%             if isappdata(peers(i),'Control')
%                 actxproxy(peers(i));
%             end            
%         end
end

function result = local_isInvokeActiveXCallback(gui_State, varargin)

try
    result = ispc && iscom(varargin{1}) ...
             && isequal(varargin{1},gcbo);
catch
    result = false;
end

function result = local_isInvokeHGCallback(gui_State, varargin)

try
    fhandle = functions(gui_State.gui_Callback);
    result = ~isempty(findstr(gui_State.gui_Name,fhandle.file)) || ...
             (ischar(varargin{1}) ...
             && isequal(ishghandle(varargin{2}), 1) ...
             && (~isempty(strfind(varargin{1},[get(varargin{2}, 'Tag'), '_'])) || ...
                ~isempty(strfind(varargin{1}, '_CreateFcn'))) );
catch
    result = false;
end


